USE quality;

INSERT INTO cm_resource (pid, NAME, widgetCode, url, menuFlag, operType, chkAuthFlag, addPerson)
(SELECT id, '质检辅助表列表', '', 'qc/auxiliaryBill/list', 1, 0, 1, '陈海涛' FROM cm_resource WHERE NAME='运营质检');

INSERT INTO cm_resource (pid, NAME, widgetCode, url, menuFlag, operType, chkAuthFlag, addPerson)
(SELECT id, '辅助表模板', '', 'qc/operateQcBill/toAuxiliaryBillTemplate', 1, 0, 1, '陈海涛' FROM cm_resource WHERE NAME='运营质检');

DROP TABLE IF EXISTS qc_auxiliary_bill_template;
CREATE TABLE `qc_auxiliary_bill_template` (
   `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'PK',
   `qcType` INT(11) NOT NULL DEFAULT '0' COMMENT '质检类型ID',
  `fieldName1` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称1',
  `fieldName2` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称2',
  `fieldName3` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称3',
  `fieldName4` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称4',
  `fieldName5` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称5',
  `fieldName6` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称6',
  `fieldName7` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称7',
  `fieldName8` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称8',
  `fieldName9` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称9',
  `fieldName10` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称10',
  `fieldName11` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称11',
  `fieldName12` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称12',
  `fieldName13` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称13',
  `fieldName14` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称14',
  `fieldName15` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称15',
  `fieldName16` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称16',
  `fieldName17` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称17',
  `fieldName18` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称18',
  `fieldName19` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称19',
  `fieldName20` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称20',
  `fieldName21` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称21',
  `fieldName22` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称22',
  `fieldName23` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称23',
  `fieldName24` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称24',
  `fieldName25` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称25',
  `fieldName26` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称26',
  `fieldName27` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称27',
  `fieldName28` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称28',
  `fieldName29` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称29',
  `fieldName30` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '字段名称30',
   `addPerson` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '添加人',
   `addTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
   `updatePerson` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '修改人',
   `updateTime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '修改时间',
   `delFlag` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '删除标识位，0：未删除，1：已删除'
) ENGINE=INNODB  DEFAULT CHARSET=utf8 COMMENT='运营质检辅助表模板';

DROP TABLE IF EXISTS qc_auxiliary_bill;
CREATE TABLE `qc_auxiliary_bill` (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'PK',
  `templateId` INT(11) NOT NULL DEFAULT '0' COMMENT '模板ID',
  `qcId` INT(11) NOT NULL DEFAULT '0' COMMENT '质检单号',
  `field1` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值1',
  `field2` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值2',
  `field3` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值3',
  `field4` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值4',
  `field5` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值5',
  `field6` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值6',
  `field7` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值7',
  `field8` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值8',
  `field9` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值9',
  `field10` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值10',
  `field11` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值11',
  `field12` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值12',
  `field13` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值13',
  `field14` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值14',
  `field15` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值15',
  `field16` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值16',
  `field17` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值17',
  `field18` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值18',
  `field19` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值19',
  `field20` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值20',
  `field21` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值21',
  `field22` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值22',
  `field23` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值23',
  `field24` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值24',
  `field25` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值25',
  `field26` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值26',
  `field27` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值27',
  `field28` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值28',
  `field29` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值29',
  `field30` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '字段值30',
   `addPerson` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '添加人',
   `addTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
   `updatePerson` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '修改人',
   `updateTime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '修改时间',
   `delFlag` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '删除标识位，0：未删除，1：已删除'
) ENGINE=INNODB  DEFAULT CHARSET=utf8 COMMENT='运营质检辅助表';



  
   