function complaint_check_form(){
	var valid_obj = {
		order_come_from:{
			title:"订单来源",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		owner_partment:{
			title:"发起人所在部门",
			max_len:"100",
			auto_func:{
				type_func:"check_length"
			}
		},
		manager:{
			title:"负责人",
			auto_func:{
				type_func:"is_int"
			}
		},
		owner_name:{
			title:"发起人姓名",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		order_state:{
			title:"订单状态",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		guest_name:{
			title:"客人姓名",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		state:{
			title:"状态位",
			auto_func:{
				type_func:"is_int"
			}
		},
		order_id:{
			title:"关联订单id",
			auto_func:{
				type_func:"is_int"
			}
		},
		customer:{
			title:"售前客服",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		customer_leader:{
			title:"客服经理",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		start_city:{
			title:"出发城市",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		level:{
			title:"投诉等级",
			auto_func:{
				type_func:"is_int"
			}
		},
		deal:{
			title:"处理人",
			auto_func:{
				type_func:"is_int"
			}
		},
		route_type:{
			title:"线路类型",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		route:{
			title:"线路",
			max_len:"250",
			auto_func:{
				type_func:"check_length"
			}
		},
		product_leader:{
			title:"产品经理",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		deal_name:{
			title:"处理人姓名",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		owner_id:{
			title:"投诉发起人",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		manager_name:{
			title:"负责人姓名",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		producter:{
			title:"产品专员",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		senior_manager:{
			title:"高级经理",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		come_from:{
			title:"投诉来源",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		guest_num:{
			title:"客人数量",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		order_type:{
			title:"订单类型",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		}
	};
	return check_form(valid_obj);
}
