function gift_note_check_form(){
	var valid_obj = {
		user_name:{
			title:"申请人姓名",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		phone:{
			title:"联系电话",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		receiver:{
			title:"收件人",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		zip_code:{
			title:"邮编",
			max_len:"50",
			auto_func:{
				type_func:"check_length"
			}
		},
		address:{
			title:"收件人地址",
			max_len:"150",
			auto_func:{
				type_func:"check_length"
			}
		},
		department_id:{
			title:"部门id",
			auto_func:{
				type_func:"is_int"
			}
		},
		complaint_id:{
			title:"关联投诉id",
			auto_func:{
				type_func:"is_int"
			}
		},
		user_id:{
			title:"申请人id",
			auto_func:{
				type_func:"is_int"
			}
		},
		order_id:{
			title:"订单号",
			auto_func:{
				type_func:"is_int"
			}
		},
		department_name:{
			title:"部门名称",
			max_len:"150",
			auto_func:{
				type_func:"check_length"
			}
		}
	};
	return check_form(valid_obj);
}
