<%@page import="java.util.HashMap"%><%@page import="java.util.Map"%><%@ page language="java" contentType="text/html; charset=UTF-8"  pageEncoding="UTF-8"%><%@include file="/WEB-INF/html/head.jsp" %></HEAD><BODY>
<h2>字段管理</h2>
<form class="mb10 clear" method="POST" id="search_form" action="${manageUrl}"> 	<!-- 	<select name="table_name" id="table_name"  onChange="$('#search_form').get(0).submit();" >		<c:forEach items="${request.tableList}" var="c"> 			<option value="${c.table_name}">${c.table_name}</option>		</c:forEach>		 -->	 	<select name="table_id" id="table_id"  onChange="$('#search_form').get(0).submit();" >		${ui:makeSelect(request.tableList,request.table_id,fn:split("id,fullTableName",","))}    	</select>	</form>
<form method="POST" action="${manageUrl}-doEdit"> 
<input type="hidden" name="refer_to" value="" />
<input type="hidden" name="table_id" value="${table_id}" />   
	<table class="listtable">
		<thead>			<th>id</th>			<th>表名</th>			<th>字段名</th>			<th>详细描述</th>			<th>列表</th>			<th>列表名</th>			<th>点击</th>			<th>表单</th>			<th>表单名</th>			<th>表单样式</th>			<th>必填</th>			<th>搜索</th>			<th>搜索样式</th>			<th>缓存</th>
		</thead>
		<tbody>		<c:forEach items="${dataList}" var="v"  varStatus="st"> 			<tr>				<td>${v.id}<input type="hidden" name="fieldList[${st.index}].id"  value="${v.id}" /></td>				<td>${v.tableName}</td>				<td>${v.fieldName}</td>				<td><textarea name="fieldList[${st.index}].description" rows="2" style="width:150px;">${v.description}</textarea></td> 				<td>					<c:set var="t" value="fieldList[${st.index}].listShow" /> 					${ui:makeCheckbox(ui:str2Map("1:显示"),t,fn:split(v.listShow,","),null)} 				</td>				<td><input type="text"  name="fieldList[${st.index}].listTitle"  value="${v.listTitle}" style="width:100px;" /></td>				<td>					<c:set var="t" value="fieldList[${st.index}].titleOrder" /> 					${ui:makeCheckbox(ui:str2Map("1:排序"),t,fn:split(v.titleOrder,","),null)} 				</td>				<td>					<c:set var="t" value="fieldList[${st.index}].formShow" /> 					${ui:makeCheckbox(ui:str2Map("1:显示"),t,fn:split(v.formShow,","),null)} 				</td>				<td><input type="text" name="fieldList[${st.index}].formTitle"  value="${v.formTitle}"  style="width:100px;"/></td>								<td>					<select name="fieldList[${st.index}].formShowType" id="form_show_type_${v.id}" >						${ui:makeSelect(request.controlList,v.formShowType,fn:split("id,controlName",","))}  						</select>				</td>				<td>					<c:set var="t" value="fieldList[${st.index}].needFill" /> 					${ui:makeCheckbox(ui:str2Map("1:是"),t,fn:split(v.needFill,","),null)} 							</td>				<td>					<c:set var="t" value="fieldList[${st.index}].canSearch" /> 					${ui:makeCheckbox(ui:str2Map("1:是"),t,fn:split(v.canSearch,","),null)} 				</td>				<td>					<select name="fieldList[${st.index}].searchShowType" id="search_show_type_${v.id}" >						${ui:makeSelect(request.controlList,v.searchShowType,fn:split("id,controlName",","))} 					</select>				</td> 				<td>					<c:set var="t" value="fieldList[${st.index}].canCache" /> 					${ui:makeCheckbox(ui:str2Map("1:是"),t,fn:split(v.canCache,","),null)} 				</td>			</tr>					</c:forEach>			<tr>				<td colspan="100">					<input type="submit" name="submit1" value="提交并生成程序代码" />(已生成过的代码须手工移除后才会重新生成)										</td>			</tr>
		</tbody>	
	</table>
</form><%@include file="/WEB-INF/html/foot.jsp" %>
