function table_field_check_form(){
	var valid_obj = {
		position:{
			title:"位置",
			auto_func:{
				type_func:"is_int"
			}
		},
		field_name:{
			title:"field_name",
			max_len:"30",
			auto_func:{
				type_func:"check_length"
			}
		},
		form_show:{
			title:"form_show",
			auto_func:{
				type_func:"is_int"
			}
		},
		field_type:{
			title:"field_type",
			max_len:"64",
			auto_func:{
				type_func:"check_length"
			}
		},
		form_show_type:{
			title:"form_show_type",
			auto_func:{
				type_func:"is_int"
			}
		},
		field_def:{
			title:"field_def",
			max_len:"100",
			auto_func:{
				type_func:"check_length"
			}
		},
		list_show:{
			title:"list_show",
			auto_func:{
				type_func:"is_int"
			}
		},
		table_id:{
			title:"表id",
			auto_func:{
				type_func:"is_int"
			}
		},
		search_show_type:{
			title:"search_show_type",
			auto_func:{
				type_func:"is_int"
			}
		},
		field_attr:{
			title:"field_attr",
			max_len:"20",
			auto_func:{
				type_func:"check_length"
			}
		},
		need_fill:{
			title:"need_fill",
			auto_func:{
				type_func:"is_int"
			}
		},
		list_title:{
			title:"list_title",
			max_len:"20",
			auto_func:{
				type_func:"check_length"
			}
		},
		can_cache:{
			title:"can_cache",
			auto_func:{
				type_func:"is_int"
			}
		},
		field_length:{
			title:"field_length",
			max_len:"100",
			auto_func:{
				type_func:"check_length"
			}
		},
		can_search:{
			title:"can_search",
			auto_func:{
				type_func:"is_int"
			}
		},
		db_comment:{
			title:"db_comment",
			max_len:"255",
			auto_func:{
				type_func:"check_length"
			}
		},
		description:{
			title:"description",
			max_len:"1000",
			auto_func:{
				type_func:"check_length"
			}
		},
		title_order:{
			title:"title_order",
			auto_func:{
				type_func:"is_int"
			}
		},
		table_name:{
			title:"table_name",
			max_len:"60",
			auto_func:{
				type_func:"check_length"
			}
		},
		form_title:{
			title:"form_title",
			max_len:"20",
			auto_func:{
				type_func:"check_length"
			}
		},
		index_type:{
			title:"index_type",
			max_len:"3",
			auto_func:{
				type_func:"check_length"
			}
		}
	};
	return check_form(valid_obj);
}
