function table_check_form(){
	var valid_obj = {
		dir_path:{
			title:"dir_path",
			max_len:"255",
			auto_func:{
				type_func:"check_length"
			}
		},
		form_action:{
			title:"生成action",
			auto_func:{
				type_func:"is_int"
			}
		},
		make_form_time:{
			title:"make_form_time",
			auto_func:{
				type_func:"is_int"
			}
		},
		make_module_time:{
			title:"make_module_time",
			auto_func:{
				type_func:"is_int"
			}
		},
		table_name:{
			title:"table_name",
			max_len:"30",
			auto_func:{
				type_func:"check_length"
			}
		},
		app_id:{
			title:"应用标识,默认frm",
			max_len:"30",
			auto_func:{
				type_func:"check_length"
			}
		},
		make_list_time:{
			title:"make_list_time",
			auto_func:{
				type_func:"is_int"
			}
		},
		table_exist:{
			title:"table_exist",
			auto_func:{
				type_func:"is_int"
			}
		}
	};
	return check_form(valid_obj);
}
