function user_check_form(){
	var valid_obj = {
		tel:{
			title:"tel",
			max_len:"16",
			auto_func:{
				type_func:"check_length"
			}
		},
		dep_id:{
			title:"dep_id",
			auto_func:{
				empty_func:"check_empty",
				type_func:"is_int"
			}
		},
		can_admin:{
			title:"是否可以管理UC",
			auto_func:{
				type_func:"is_int"
			}
		},
		worknum:{
			title:"worknum",
			max_len:"6",
			auto_func:{
				empty_func:"check_empty",
				type_func:"check_length"
			}
		},
		password:{
			title:"password",
			max_len:"32",
			auto_func:{
				empty_func:"check_empty",
				type_func:"check_length"
			}
		},
		location_id:{
			title:"实际工作地点",
			auto_func:{
				type_func:"is_int"
			}
		},
		extension:{
			title:"extension",
			max_len:"6",
			auto_func:{
				type_func:"check_length"
			}
		},
		user_name:{
			title:"user_name",
			max_len:"30",
			auto_func:{
				empty_func:"check_empty",
				type_func:"check_length"
			}
		},
		blackberry_code:{
			title:"黑莓号",
			max_len:"20",
			auto_func:{
				type_func:"check_length"
			}
		},
		email:{
			title:"email",
			max_len:"60",
			auto_func:{
				empty_func:"check_empty",
				type_func:"check_length"
			}
		},
		position_id:{
			title:"position_id",
			auto_func:{
				empty_func:"check_empty",
				type_func:"is_int"
			}
		},
		real_name:{
			title:"real_name",
			max_len:"30",
			auto_func:{
				empty_func:"check_empty",
				type_func:"check_length"
			}
		},
		main_dep_seq:{
			title:"main_dep_seq",
			auto_func:{
				type_func:"is_int"
			}
		},
		mobile:{
			title:"mobile",
			max_len:"16",
			auto_func:{
				empty_func:"check_empty",
				type_func:"check_length"
			}
		},
		job_id:{
			title:"job_id",
			auto_func:{
				empty_func:"check_empty",
				type_func:"is_int"
			}
		}
	};
	return check_form(valid_obj);
}
