function check_email_check_form(){
	var valid_obj = {
		sender:{
			title:"发件人",
			max_len:"100",
			auto_func:{
				type_func:"check_length"
			}
		},
		title:{
			title:"邮件主题",
			max_len:"300",
			auto_func:{
				type_func:"check_length"
			}
		},
		attach_id:{
			title:"附件id",
			auto_func:{
				type_func:"is_int"
			}
		},
		address:{
			title:"收件人",
			max_len:"500",
			auto_func:{
				type_func:"check_length"
			}
		},
		complaint_id:{
			title:"关联订单id",
			auto_func:{
				type_func:"is_int"
			}
		},
		mark:{
			title:"标示位，0发送，1为回复",
			auto_func:{
				type_func:"is_int"
			}
		},
		cc:{
			title:"抄送人",
			max_len:"500",
			auto_func:{
				type_func:"check_length"
			}
		}
	};
	return check_form(valid_obj);
}
